export const navigationDrawer = [
    { icon: "mdi-contacts", text: "Forgets" ,alias:"/kod-listesi"  },
    { icon: "mdi-history", text: "Categories" , alias:"/kategoriler" },
    // { icon: "mdi-content-copy", text: "Duplicates" },
    // {
    //     icon: "mdi-chevron-up",
    //     "icon-alt": "mdi-chevron-down",
    //     text: "Labels",
    //     model: true,
    //     children: [{ icon: "mdi-plus", text: "Create label" }],
    // },
    // {
    //     icon: "mdi-chevron-up",
    //     "icon-alt": "mdi-chevron-down",
    //     text: "More",
    //     model: false,
    //     children: [
    //         { text: "Import" },
    //         { text: "Export" },
    //         { text: "Print" },
    //         { text: "Undo changes" },
    //         { text: "Other contacts" },
    //     ],
    // },
    // { icon: "mdi-cog", text: "Settings" },
    // { icon: "mdi-message", text: "Send feedback" },
    // { icon: "mdi-help-circle", text: "Help" },
    // { icon: "mdi-cellphone-link", text: "App downloads" },
    // { icon: "mdi-keyboard", text: "Go to the old version" },
];